"use client";

import React, { useState, useMemo } from "react";
import { LegalBriefData } from "@/app/api/generate-brief/route";
import {
  Clock,
  HelpCircle,
  CheckCircle2,
  AlertOctagon,
  Copy,
  Check,
  Download,
  Tag,
  UserCheck,
  Calendar,
  Layers,
} from "lucide-react";
import { DisclaimerBanner } from "./DisclaimerBanner";

interface LegalBriefOutputProps {
  brief: LegalBriefData;
}

export const LegalBriefOutput: React.FC<LegalBriefOutputProps> = ({ brief }) => {
  const [activeTab, setActiveTab] = useState<
    "all" | "timeline" | "missing" | "nextsteps"
  >("all");
  const [copied, setCopied] = useState(false);

  // Generate plain text version for copy/speech with memoization for Efficiency
  const speechText = useMemo(() => {
    let text = `Executive Brief Summary: ${brief.caseSummary}. Legal Category: ${brief.legalCategory}. `;

    text += "Chronological Timeline: ";
    brief.timeline.forEach((item, index) => {
      text += `Event ${index + 1}: ${item.date} - ${item.title}. Details: ${item.details}. Parties: ${item.keyParties}. `;
    });

    text += "Missing Critical Facts: ";
    brief.missingFacts.forEach((fact, index) => {
      text += `Fact ${index + 1}: ${fact.question}. Rationale: ${fact.rationale}. Importance: ${fact.importance}. `;
    });

    text += "Informational Next Steps: ";
    brief.nextSteps.forEach((step) => {
      text += `Step ${step.stepNumber}: ${step.action}. Urgency: ${step.urgency}. `;
    });

    return text;
  }, [brief]);

  const handleCopy = () => {
    const markdown = `# AOR LEGAL BRIEFING SUMMARY
Generated by AOR-Briefing Assistant (Pre-Consultation Tool)
Legal Category: ${brief.legalCategory}

## Executive Summary
${brief.caseSummary}

## Key Risk & Procedural Factors
${brief.legalRiskFactors.map((rf) => `- ${rf}`).join("\n")}

## Chronological Timeline
${brief.timeline
  .map(
    (t, i) =>
      `${i + 1}. [${t.date}] ${t.title}\n   Details: ${t.details}\n   Parties: ${t.keyParties}${
        t.evidenceRef ? `\n   Evidence Ref: ${t.evidenceRef}` : ""
      }`
  )
  .join("\n\n")}

## Missing Critical Facts
${brief.missingFacts
  .map(
    (m, i) =>
      `${i + 1}. [${m.importance} Priority] ${m.question}\n   Category: ${m.category}\n   Rationale: ${m.rationale}`
  )
  .join("\n\n")}

## Informational Next Steps Before Consultation
${brief.nextSteps
  .map(
    (ns) =>
      `Step ${ns.stepNumber}: ${ns.action} (${ns.urgency})\n   Category: ${ns.category}\n   Rationale: ${ns.rationale}`
  )
  .join("\n\n")}

---
DISCLAIMER: This tool provides informational structuring only and does not constitute legal advice.
`;

    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([speechText], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = `AOR_Legal_Brief_${brief.legalCategory.replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const getImportanceBadge = (imp: "High" | "Medium" | "Low") => {
    switch (imp) {
      case "High":
        return "bg-red-500/20 text-red-300 border-red-500/40";
      case "Medium":
        return "bg-amber-500/20 text-amber-300 border-amber-500/40";
      default:
        return "bg-blue-500/20 text-blue-300 border-blue-500/40";
    }
  };

  const getUrgencyBadge = (urg: string) => {
    if (urg.includes("Immediate")) {
      return "bg-red-500/20 text-red-300 border-red-500/50";
    }
    if (urg.includes("High")) {
      return "bg-amber-500/20 text-amber-300 border-amber-500/50";
    }
    return "bg-slate-800 text-slate-200 border-slate-700";
  };

  return (
    <div className="space-y-6">
      {/* Executive Summary Card */}
      <section
        aria-label="Executive Case Brief Section"
        className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden"
      >
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4 mb-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-bold text-amber-300 bg-amber-500/20 px-2.5 py-0.5 rounded-full border border-amber-500/30">
                {brief.legalCategory}
              </span>
              <span className="text-xs text-slate-300">• Structured Legal Output</span>
            </div>
            <h2 className="text-xl font-bold text-white">Executive Case Brief</h2>
          </div>

          {/* Actions: Copy & Download */}
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              aria-label="Copy legal brief to clipboard in markdown format"
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-100 rounded-lg text-xs font-bold border border-slate-700 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" aria-hidden="true" />
                  <span className="text-emerald-400 font-bold">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" aria-hidden="true" />
                  <span>Copy Brief</span>
                </>
              )}
            </button>

            <button
              type="button"
              onClick={handleDownload}
              aria-label="Export brief as text file"
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-100 rounded-lg text-xs font-bold border border-slate-700 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400"
            >
              <Download className="w-3.5 h-3.5" aria-hidden="true" />
              <span>Export Text</span>
            </button>
          </div>
        </div>

        {/* Narrative Summary */}
        <p className="text-slate-200 text-sm leading-relaxed mb-4 font-normal">
          {brief.caseSummary}
        </p>

        {/* Risk Factors */}
        {brief.legalRiskFactors && brief.legalRiskFactors.length > 0 && (
          <div className="bg-amber-950/30 border border-amber-500/40 rounded-xl p-3">
            <span className="text-xs font-bold text-amber-300 flex items-center gap-1.5 mb-2">
              <AlertOctagon className="w-4 h-4 text-amber-400" aria-hidden="true" />
              Legal Risk & Procedural Factors Identified:
            </span>
            <div className="flex flex-wrap gap-2">
              {brief.legalRiskFactors.map((risk, i) => (
                <span
                  key={i}
                  className="text-xs bg-amber-500/20 text-amber-200 font-semibold border border-amber-500/30 px-2.5 py-1 rounded-lg"
                >
                  ⚠️ {risk}
                </span>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* ARIA Accessible Tabs Switcher */}
      <div
        role="tablist"
        aria-label="Brief Content Views"
        className="flex items-center gap-2 border-b border-slate-800 overflow-x-auto pb-2"
      >
        <button
          role="tab"
          id="tab-all"
          aria-selected={activeTab === "all"}
          aria-controls="panel-brief-content"
          onClick={() => setActiveTab("all")}
          className={`px-4 py-2 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 ${
            activeTab === "all"
              ? "bg-amber-400 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-300 hover:text-slate-100"
          }`}
        >
          <Layers className="w-3.5 h-3.5" aria-hidden="true" />
          <span>Full Overview</span>
        </button>

        <button
          role="tab"
          id="tab-timeline"
          aria-selected={activeTab === "timeline"}
          aria-controls="panel-brief-content"
          onClick={() => setActiveTab("timeline")}
          className={`px-4 py-2 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 ${
            activeTab === "timeline"
              ? "bg-amber-400 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-300 hover:text-slate-100"
          }`}
        >
          <Clock className="w-3.5 h-3.5" aria-hidden="true" />
          <span>Chronological Timeline ({brief.timeline.length})</span>
        </button>

        <button
          role="tab"
          id="tab-missing"
          aria-selected={activeTab === "missing"}
          aria-controls="panel-brief-content"
          onClick={() => setActiveTab("missing")}
          className={`px-4 py-2 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 ${
            activeTab === "missing"
              ? "bg-amber-400 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-300 hover:text-slate-100"
          }`}
        >
          <HelpCircle className="w-3.5 h-3.5" aria-hidden="true" />
          <span>Missing Facts ({brief.missingFacts.length})</span>
        </button>

        <button
          role="tab"
          id="tab-nextsteps"
          aria-selected={activeTab === "nextsteps"}
          aria-controls="panel-brief-content"
          onClick={() => setActiveTab("nextsteps")}
          className={`px-4 py-2 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 ${
            activeTab === "nextsteps"
              ? "bg-amber-400 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-300 hover:text-slate-100"
          }`}
        >
          <CheckCircle2 className="w-3.5 h-3.5" aria-hidden="true" />
          <span>Next Steps ({brief.nextSteps.length})</span>
        </button>
      </div>

      <div id="panel-brief-content" role="tabpanel" className="space-y-6">
        {/* SECTION 1: CHRONOLOGICAL TIMELINE */}
        {(activeTab === "all" || activeTab === "timeline") && (
          <section
            aria-label="Chronological Timeline Section"
            className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl"
          >
            <div className="flex items-center gap-2 mb-6">
              <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center">
                <Clock className="w-4 h-4 text-indigo-400" aria-hidden="true" />
              </div>
              <div>
                <h3 className="text-base font-bold text-white">
                  1. Chronological Timeline of Events
                </h3>
                <p className="text-xs text-slate-300">
                  Key incidents mapped sequentially for advocate review
                </p>
              </div>
            </div>

            <div className="relative pl-6 sm:pl-8 border-l-2 border-indigo-500/40 space-y-8">
              {brief.timeline.map((event, index) => (
                <article key={index} className="relative group">
                  <div className="absolute -left-[31px] sm:-left-[39px] top-1.5 w-4 h-4 rounded-full bg-slate-950 border-2 border-indigo-500 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                  </div>

                  <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 shadow-md">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-2">
                      <span className="text-xs font-bold text-amber-300 flex items-center gap-1.5 bg-amber-500/20 px-2.5 py-0.5 rounded-md border border-amber-500/30 w-fit">
                        <Calendar className="w-3 h-3" aria-hidden="true" />
                        {event.date}
                      </span>
                      <span className="text-xs text-slate-300 flex items-center gap-1 font-medium">
                        <UserCheck className="w-3 h-3 text-indigo-400" aria-hidden="true" />
                        Parties: {event.keyParties}
                      </span>
                    </div>

                    <h4 className="text-sm font-bold text-slate-100 mb-1.5">
                      {event.title}
                    </h4>

                    <p className="text-xs text-slate-200 leading-relaxed mb-2 font-normal">
                      {event.details}
                    </p>

                    {event.evidenceRef && (
                      <div className="inline-flex items-center gap-1.5 text-[11px] bg-indigo-950/70 text-indigo-200 border border-indigo-500/40 px-2.5 py-1 rounded-md font-semibold">
                        <Tag className="w-3 h-3" aria-hidden="true" />
                        <span>Evidence / Proof: {event.evidenceRef}</span>
                      </div>
                    )}
                  </div>
                </article>
              ))}
            </div>
          </section>
        )}

        {/* SECTION 2: MISSING CRITICAL FACTS */}
        {(activeTab === "all" || activeTab === "missing") && (
          <section
            aria-label="Missing Critical Facts Section"
            className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl"
          >
            <div className="flex items-center gap-2 mb-6">
              <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center">
                <HelpCircle className="w-4 h-4 text-amber-400" aria-hidden="true" />
              </div>
              <div>
                <h3 className="text-base font-bold text-white">
                  2. Missing Critical Facts & Information Gaps
                </h3>
                <p className="text-xs text-slate-300">
                  Crucial queries the advocate will evaluate before taking action
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {brief.missingFacts.map((fact, index) => (
                <div
                  key={index}
                  className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <span className="text-[10px] uppercase tracking-wider font-bold text-slate-300 bg-slate-900 px-2 py-0.5 rounded border border-slate-700">
                        {fact.category}
                      </span>
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getImportanceBadge(
                          fact.importance
                        )}`}
                      >
                        {fact.importance} Priority Gap
                      </span>
                    </div>

                    <h4 className="text-sm font-bold text-amber-300 mb-2 flex items-start gap-2">
                      <span className="text-slate-400 shrink-0">Q{index + 1}.</span>
                      <span>{fact.question}</span>
                    </h4>
                  </div>

                  <div className="mt-3 pt-3 border-t border-slate-800 text-xs text-slate-300 bg-slate-900/60 p-2.5 rounded-lg">
                    <strong className="text-slate-200 block mb-0.5 font-bold">
                      Why Legal Counsel Needs This:
                    </strong>
                    <p className="font-normal text-slate-300">{fact.rationale}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* SECTION 3: INFORMATIONAL NEXT STEPS */}
        {(activeTab === "all" || activeTab === "nextsteps") && (
          <section
            aria-label="Informational Next Steps Section"
            className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl"
          >
            <div className="flex items-center gap-2 mb-6">
              <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" aria-hidden="true" />
              </div>
              <div>
                <h3 className="text-base font-bold text-white">
                  3. Informational Next Steps Before Consultation
                </h3>
                <p className="text-xs text-slate-300">
                  Preparation checklist to maximize your advocate consultation efficiency
                </p>
              </div>
            </div>

            <div className="space-y-4">
              {brief.nextSteps.map((step) => (
                <div
                  key={step.stepNumber}
                  className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 flex flex-col sm:flex-row items-start gap-4"
                >
                  <div className="w-9 h-9 rounded-xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-300 font-extrabold flex items-center justify-center shrink-0">
                    {step.stepNumber}
                  </div>

                  <div className="flex-1">
                    <div className="flex flex-wrap items-center justify-between gap-2 mb-1">
                      <span className="text-xs font-bold text-slate-300">
                        Category: {step.category}
                      </span>
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getUrgencyBadge(
                          step.urgency
                        )}`}
                      >
                        {step.urgency}
                      </span>
                    </div>

                    <h4 className="text-sm font-bold text-slate-100 mb-1">
                      {step.action}
                    </h4>

                    <p className="text-xs text-slate-200 leading-relaxed font-normal">
                      <span className="text-slate-300 font-bold">Objective: </span>
                      {step.rationale}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}
      </div>

      {/* PERSISTENT LEGAL DISCLAIMER CARD AT BOTTOM */}
      <DisclaimerBanner variant="card" />
    </div>
  );
};
