"use client";

import React, { useState } from "react";
import { LegalBriefData } from "@/app/api/generate-brief/route";
import {
  Clock,
  HelpCircle,
  CheckCircle2,
  AlertOctagon,
  FileSpreadsheet,
  Copy,
  Check,
  Download,
  Printer,
  ShieldCheck,
  Tag,
  UserCheck,
  Calendar,
  Layers,
  ArrowRight,
} from "lucide-react";
import { DisclaimerBanner } from "./DisclaimerBanner";

interface LegalBriefOutputProps {
  brief: LegalBriefData;
}

export const LegalBriefOutput: React.FC<LegalBriefOutputProps> = ({ brief }) => {
  const [activeTab, setActiveTab] = useState<
    "all" | "timeline" | "missing" | "nextsteps" | "lawyer"
  >("all");
  const [copied, setCopied] = useState(false);

  // Generate plain text version for copy/speech
  const generateFullTextForSpeech = () => {
    let text = `Executive Brief Summary: ${brief.caseSummary}. Legal Category: ${brief.legalCategory}. `;

    text += "Chronological Timeline: ";
    brief.timeline.forEach((item, index) => {
      text += `Event ${index + 1}: ${item.date} - ${item.title}. Details: ${item.details}. Parties: ${item.keyParties}. `;
    });

    text += "Missing Critical Facts: ";
    brief.missingFacts.forEach((fact, index) => {
      text += `Fact ${index + 1}: ${fact.question}. Rationale: ${fact.rationale}. Importance: ${fact.importance}. `;
    });

    text += "Informational Next Steps: ";
    brief.nextSteps.forEach((step) => {
      text += `Step ${step.stepNumber}: ${step.action}. Urgency: ${step.urgency}. `;
    });

    return text;
  };

  const handleCopy = () => {
    const markdown = `# AOR LEGAL BRIEFING SUMMARY
Generated by AOR-Briefing Assistant (Pre-Consultation Tool)
Legal Category: ${brief.legalCategory}

## Executive Summary
${brief.caseSummary}

## Key Risk & Procedural Factors
${brief.legalRiskFactors.map((rf) => `- ${rf}`).join("\n")}

## Chronological Timeline
${brief.timeline
  .map(
    (t, i) =>
      `${i + 1}. [${t.date}] ${t.title}\n   Details: ${t.details}\n   Parties: ${t.keyParties}${
        t.evidenceRef ? `\n   Evidence Ref: ${t.evidenceRef}` : ""
      }`
  )
  .join("\n\n")}

## Missing Critical Facts
${brief.missingFacts
  .map(
    (m, i) =>
      `${i + 1}. [${m.importance} Priority] ${m.question}\n   Category: ${m.category}\n   Rationale: ${m.rationale}`
  )
  .join("\n\n")}

## Informational Next Steps Before Consultation
${brief.nextSteps
  .map(
    (ns) =>
      `Step ${ns.stepNumber}: ${ns.action} (${ns.urgency})\n   Category: ${ns.category}\n   Rationale: ${ns.rationale}`
  )
  .join("\n\n")}

---
DISCLAIMER: This document provides informational structuring only and does not constitute legal advice.
`;

    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const markdown = `# AOR LEGAL BRIEFING SUMMARY\nCategory: ${brief.legalCategory}\n\nSummary:\n${brief.caseSummary}\n\n...`;
    const file = new Blob([generateFullTextForSpeech()], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = `AOR_Legal_Brief_${brief.legalCategory.replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const getImportanceBadge = (imp: "High" | "Medium" | "Low") => {
    switch (imp) {
      case "High":
        return "bg-red-500/10 text-red-400 border-red-500/30";
      case "Medium":
        return "bg-amber-500/10 text-amber-400 border-amber-500/30";
      default:
        return "bg-blue-500/10 text-blue-400 border-blue-500/30";
    }
  };

  const getUrgencyBadge = (urg: string) => {
    if (urg.includes("Immediate")) {
      return "bg-red-500/15 text-red-300 border-red-500/40";
    }
    if (urg.includes("High")) {
      return "bg-amber-500/15 text-amber-300 border-amber-500/40";
    }
    return "bg-slate-800 text-slate-300 border-slate-700";
  };

  return (
    <div className="space-y-6">
      {/* Executive Summary Card */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4 mb-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-bold text-amber-400 bg-amber-500/10 px-2.5 py-0.5 rounded-full border border-amber-500/20">
                {brief.legalCategory}
              </span>
              <span className="text-xs text-slate-400">• Structured Legal Output</span>
            </div>
            <h2 className="text-xl font-bold text-white">Executive Case Brief</h2>
          </div>

          {/* Actions: Copy & Download */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium border border-slate-700 transition-all"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400 font-semibold">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Brief</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium border border-slate-700 transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Text</span>
            </button>
          </div>
        </div>

        {/* Narrative Summary */}
        <p className="text-slate-300 text-sm leading-relaxed mb-4">
          {brief.caseSummary}
        </p>

        {/* Risk Factors */}
        {brief.legalRiskFactors && brief.legalRiskFactors.length > 0 && (
          <div className="bg-amber-950/20 border border-amber-500/30 rounded-xl p-3">
            <span className="text-xs font-bold text-amber-400 flex items-center gap-1.5 mb-2">
              <AlertOctagon className="w-4 h-4" />
              Legal Risk & Procedural Factors Identified:
            </span>
            <div className="flex flex-wrap gap-2">
              {brief.legalRiskFactors.map((risk, i) => (
                <span
                  key={i}
                  className="text-xs bg-amber-500/10 text-amber-200 border border-amber-500/20 px-2.5 py-1 rounded-lg"
                >
                  ⚠️ {risk}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Tabs Switcher */}
      <div className="flex items-center gap-2 border-b border-slate-800 overflow-x-auto pb-2">
        <button
          onClick={() => setActiveTab("all")}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
            activeTab === "all"
              ? "bg-amber-500 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-400 hover:text-slate-200"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>Full Overview</span>
        </button>

        <button
          onClick={() => setActiveTab("timeline")}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
            activeTab === "timeline"
              ? "bg-amber-500 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-400 hover:text-slate-200"
          }`}
        >
          <Clock className="w-3.5 h-3.5" />
          <span>Chronological Timeline ({brief.timeline.length})</span>
        </button>

        <button
          onClick={() => setActiveTab("missing")}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
            activeTab === "missing"
              ? "bg-amber-500 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-400 hover:text-slate-200"
          }`}
        >
          <HelpCircle className="w-3.5 h-3.5" />
          <span>Missing Facts ({brief.missingFacts.length})</span>
        </button>

        <button
          onClick={() => setActiveTab("nextsteps")}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all whitespace-nowrap ${
            activeTab === "nextsteps"
              ? "bg-amber-500 text-slate-950 shadow-md"
              : "bg-slate-900 text-slate-400 hover:text-slate-200"
          }`}
        >
          <CheckCircle2 className="w-3.5 h-3.5" />
          <span>Next Steps ({brief.nextSteps.length})</span>
        </button>
      </div>

      {/* SECTION 1: CHRONOLOGICAL TIMELINE */}
      {(activeTab === "all" || activeTab === "timeline") && (
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-6">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center">
              <Clock className="w-4 h-4 text-indigo-400" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                1. Chronological Timeline of Events
              </h3>
              <p className="text-xs text-slate-400">
                Key incidents mapped sequentially for advocate review
              </p>
            </div>
          </div>

          {/* Vertical Timeline list */}
          <div className="relative pl-6 sm:pl-8 border-l-2 border-indigo-500/30 space-y-8">
            {brief.timeline.map((event, index) => (
              <div key={index} className="relative group">
                {/* Timeline Dot Marker */}
                <div className="absolute -left-[31px] sm:-left-[39px] top-1.5 w-4 h-4 rounded-full bg-slate-950 border-2 border-indigo-500 group-hover:border-amber-400 group-hover:scale-110 transition-all flex items-center justify-center">
                  <div className="w-1.5 h-1.5 rounded-full bg-indigo-400 group-hover:bg-amber-400" />
                </div>

                {/* Card Container */}
                <div className="bg-slate-950/70 border border-slate-800 hover:border-indigo-500/40 rounded-xl p-4 transition-all shadow-md">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-2">
                    <span className="text-xs font-bold text-amber-400 flex items-center gap-1.5 bg-amber-500/10 px-2.5 py-0.5 rounded-md border border-amber-500/20 w-fit">
                      <Calendar className="w-3 h-3" />
                      {event.date}
                    </span>
                    <span className="text-xs text-slate-400 flex items-center gap-1">
                      <UserCheck className="w-3 h-3 text-indigo-400" />
                      Parties: {event.keyParties}
                    </span>
                  </div>

                  <h4 className="text-sm font-bold text-slate-100 mb-1.5">
                    {event.title}
                  </h4>

                  <p className="text-xs text-slate-300 leading-relaxed mb-2">
                    {event.details}
                  </p>

                  {event.evidenceRef && (
                    <div className="inline-flex items-center gap-1.5 text-[11px] bg-indigo-950/50 text-indigo-300 border border-indigo-500/30 px-2.5 py-1 rounded-md">
                      <Tag className="w-3 h-3" />
                      <span>Evidence / Proof: {event.evidenceRef}</span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SECTION 2: MISSING CRITICAL FACTS */}
      {(activeTab === "all" || activeTab === "missing") && (
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-6">
            <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center">
              <HelpCircle className="w-4 h-4 text-amber-400" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                2. Missing Critical Facts & Information Gaps
              </h3>
              <p className="text-xs text-slate-400">
                Crucial queries the advocate will evaluate before taking action
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {brief.missingFacts.map((fact, index) => (
              <div
                key={index}
                className="bg-slate-950/70 border border-slate-800 hover:border-amber-500/40 rounded-xl p-4 flex flex-col justify-between transition-all"
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-2">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-slate-400 bg-slate-900 px-2 py-0.5 rounded">
                      {fact.category}
                    </span>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getImportanceBadge(
                        fact.importance
                      )}`}
                    >
                      {fact.importance} Priority Gap
                    </span>
                  </div>

                  <h4 className="text-sm font-bold text-amber-300 mb-2 flex items-start gap-2">
                    <span className="text-slate-500 shrink-0">Q{index + 1}.</span>
                    <span>{fact.question}</span>
                  </h4>
                </div>

                <div className="mt-3 pt-3 border-t border-slate-800/80 text-xs text-slate-400 bg-slate-900/40 p-2.5 rounded-lg">
                  <strong className="text-slate-300 block mb-0.5 font-medium">
                    Why Legal Counsel Needs This:
                  </strong>
                  <p>{fact.rationale}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SECTION 3: INFORMATIONAL NEXT STEPS */}
      {(activeTab === "all" || activeTab === "nextsteps") && (
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl">
          <div className="flex items-center gap-2 mb-6">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                3. Informational Next Steps Before Consultation
              </h3>
              <p className="text-xs text-slate-400">
                Preparation checklist to maximize your advocate consultation efficiency
              </p>
            </div>
          </div>

          <div className="space-y-4">
            {brief.nextSteps.map((step) => (
              <div
                key={step.stepNumber}
                className="bg-slate-950/70 border border-slate-800 hover:border-emerald-500/40 rounded-xl p-4 flex flex-col sm:flex-row items-start gap-4 transition-all"
              >
                <div className="w-9 h-9 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-extrabold flex items-center justify-center shrink-0">
                  {step.stepNumber}
                </div>

                <div className="flex-1">
                  <div className="flex flex-wrap items-center justify-between gap-2 mb-1">
                    <span className="text-xs font-semibold text-slate-400">
                      Category: {step.category}
                    </span>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getUrgencyBadge(
                        step.urgency
                      )}`}
                    >
                      {step.urgency}
                    </span>
                  </div>

                  <h4 className="text-sm font-bold text-slate-100 mb-1">
                    {step.action}
                  </h4>

                  <p className="text-xs text-slate-300 leading-relaxed">
                    <span className="text-slate-400 font-medium">Objective: </span>
                    {step.rationale}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* PERSISTENT LEGAL DISCLAIMER CARD AT BOTTOM */}
      <DisclaimerBanner variant="card" />
    </div>
  );
};
